Repository kubesphere-sigs/ks-devops-plugin, pull requests merged in 2021-07, with the labels that each got.

#2 Add OWNERS file in the root directory
  OWNERS
Labels: lgtm, size/XS

#1 Change image tag of ks-devops-plugin-apiserver into master
  charts/ks-devops-plugin/values.yaml
Labels: approved, lgtm, size/XS

#3 Extract authentication jwtSecret as a variable
  charts/ks-devops-plugin/templates/config.yaml
  charts/ks-devops-plugin/values.yaml
Labels: approved, lgtm, size/XS

#5 Add DevOps configuration into devops-plugin-config configmap
  charts/ks-devops-plugin/templates/config.yaml
Labels: approved, lgtm, size/XS

#4 Add multiple registries support
  README.md
  charts/ks-devops-plugin/README.md
  charts/ks-devops-plugin/templates/deployment.yaml
  charts/ks-devops-plugin/values.yaml
Labels: approved, lgtm, size/S

#7 Migrate kapis resources.kubesphere.io
  .gitpod.yml
  go.mod
  go.sum
  pkg/api/resource/v1alpha2/types.go
  pkg/apiserver/apiserver.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha1/fake/fake_tenant_client.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha1/tenant_client.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha1/workspace.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha2/fake/fake_tenant_client.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha2/tenant_client.go
  pkg/client/clientset/versioned/typed/tenant/v1alpha2/workspacetemplate.go
  pkg/client/informers/externalversions/tenant/v1alpha1/workspace.go
  pkg/client/informers/externalversions/tenant/v1alpha2/workspacetemplate.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/kapis/resources/v1alpha2/register.go
  pkg/kapis/resources/v1alpha3/handler.go
  pkg/kapis/resources/v1alpha3/register.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/resources/v1alpha2/interface.go
  pkg/models/resources/v1alpha2/namespace/namespaces.go
  pkg/models/resources/v1alpha2/resource/resources.go
  pkg/models/resources/v1alpha2/s2buildertemplate/s2ibuildertemplate.go
  pkg/models/resources/v1alpha2/s2ibuilder/s2ibuilder.go
  pkg/models/resources/v1alpha2/s2irun/s2irun.go
  pkg/models/types.go
Labels: approved, lgtm, size/XXL
